export const availableWords = [
	'Apple',
	'House',
	'Ball',
	'Cat',
	'Car',
	'Sun',
	'Book',
	'Table',
	'Chair',
	'Tree',
	'Computer',
	'Phone',
	'Dog',
	'Door',
	'Window',
	'Ocean',
	'Mountain',
	'River',
	'Lake',
	'Beach',
	'Guitar',
	'Music',
	'Coffee',
	'Tea',
	'Pizza',
	'Cake',
	'Ice cream',
	'Banana',
	'Orange',
	'Lemon',
	'School',
	'Student',
	'Teacher',
	'Library',
	'Park',
	'City',
	'Country',
	'Planet',
	'Star',
	'Moon',
	'Key',
	'Lock',
	'Bicycle',
	'Train',
	'Airplane',
	'Ship',
	'Map',
	'Compass',
	'Clock',
	'Watch',
	'Friend',
	'Family',
	'Love',
	'Happiness',
	'Hope',
	'Dream',
	'Adventure',
	'Journey',
	'Memory',
	'Experience',
	'Fire',
	'Water',
	'Earth',
	'Wind',
	'Rain',
	'Snow',
	'Ice',
	'Sand',
	'Stone',
	'Wood',
	'Soccer',
	'Basketball',
	'Tennis',
	'Swimming',
	'Running',
	'Cycling',
	'Hiking',
	'Fishing',
	'Skiing',
	'Skating',
	'Doctor',
	'Hospital',
	'Medicine',
	'Health',
	'Disease',
	'Patient',
	'Therapist',
	'Surgery',
	'Treatment',
	'Recovery',
	'Art',
	'Painting',
	'Sculpture',
	'Dance',
	'Theater',
	'Film',
	'Photography',
	'Poetry',
	'Novel',
	'Story',
	'Fairy tale',
	'Legend',
	'Myth',
	'History',
	'Future',
	'Past',
	'Present',
	'Now',
	'Tomorrow',
	'Yesterday',
	'Week',
	'Month',
	'Year',
	'Decade',
	'Century',
	'Age',
	'Child',
	'Adult',
	'Old',
	'Young',
	'Rich',
	'Poor',
	'Happy',
	'Sad',
	'Angry',
	'Fear',
	'Courage',
	'Kindness',
	'Generosity',
	'Wisdom'
];

export const availableCountries = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kosovo',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe'
];
export const words = [
	{
		english: 'apple',
		turkish: 'elma',
		category: 'Fruits',
		difficulty: 1,
		exampleSentences: ['I ate an apple for breakfast.', 'She likes green apples.'],
		etymology: "The word 'apple' comes from Old English æppel, which is of Germanic origin.",
		additionalInformation: 'Apples are rich in fiber and vitamin C.'
	},
	{
		english: 'cat',
		turkish: 'kedi',
		category: 'Animals',
		difficulty: 3,
		exampleSentences: ['The cat is sleeping.', 'She has a black and white cat.'],
		etymology: "The word 'cat' comes from Old English catt, which is of Germanic origin.",
		additionalInformation: 'Cats are popular pets around the world.'
	},
	{
		english: 'tree',
		turkish: 'ağaç',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The tree provides shade in the park.', 'I climbed a tree when I was a child.'],
		etymology: "The word 'tree' has Old English origins.",
		additionalInformation: 'Trees produce oxygen and help maintain ecological balance.'
	},
	{
		english: 'computer',
		turkish: 'bilgisayar',
		category: 'Technology',
		difficulty: 2,
		exampleSentences: ['I use my computer for work.', 'She bought a new computer last week.'],
		etymology: "The word 'computer' comes from Latin computare, meaning 'to calculate'.",
		additionalInformation: 'Computers process data and perform various tasks based on instructions.'
	},
	{
		english: 'book',
		turkish: 'kitap',
		category: 'Education',
		difficulty: 1,
		exampleSentences: ['I love reading books in my free time.', 'She borrowed a book from the library.'],
		etymology: "The word 'book' has Old English origins.",
		additionalInformation: 'Books contain knowledge and stories, and they are important for learning.'
	},
	{
		english: 'sun',
		turkish: 'güneş',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The sun is shining brightly.', 'She enjoys watching the sunset.'],
		etymology: "The word 'sun' has Old English origins.",
		additionalInformation: 'The sun is the star at the center of our solar system.'
	},
	{
		english: 'house',
		turkish: 'ev',
		category: 'Home',
		difficulty: 1,
		exampleSentences: ['I live in a small house.', 'She is cleaning the house.'],
		etymology: "The word 'house' has Old English origins.",
		additionalInformation: 'A house is a building where people live.'
	},
	{
		english: 'ball',
		turkish: 'top',
		category: 'Sports',
		difficulty: 1,
		exampleSentences: ['The children are playing with a ball.', 'She kicked the ball into the goal.'],
		etymology: "The word 'ball' has Old English origins.",
		additionalInformation: 'Balls are used in various sports and games.'
	},
	{
		english: 'car',
		turkish: 'araba',
		category: 'Transportation',
		difficulty: 1,
		exampleSentences: ['I drive a car to work.', 'She bought a new car last month.'],
		etymology: "The word 'car' has Middle English origins.",
		additionalInformation: 'Cars are a common mode of transportation.'
	},
	{
		english: 'phone',
		turkish: 'telefon',
		category: 'Technology',
		difficulty: 1,
		exampleSentences: ['I use my phone to call my friends.', 'She lost her phone yesterday.'],
		etymology: "The word 'phone' is short for 'telephone'.",
		additionalInformation: 'Phones are used for communication and various other purposes.'
	},
	{
		english: 'dog',
		turkish: 'köpek',
		category: 'Animals',
		difficulty: 1,
		exampleSentences: ['The dog is barking.', 'She has a cute little dog.'],
		etymology: "The word 'dog' has Old English origins.",
		additionalInformation: 'Dogs are loyal companions and popular pets.'
	},
	{
		english: 'door',
		turkish: 'kapı',
		category: 'Home',
		difficulty: 1,
		exampleSentences: ['Please close the door.', 'She knocked on the door.'],
		etymology: "The word 'door' has Old English origins.",
		additionalInformation: 'Doors provide security and privacy in buildings.'
	},
	{
		english: 'window',
		turkish: 'pencere',
		category: 'Home',
		difficulty: 1,
		exampleSentences: ['She opened the window to let in fresh air.', 'I looked out the window and saw a bird.'],
		etymology: "The word 'window' has Old Norse origins.",
		additionalInformation: 'Windows allow light and air to enter a room.'
	},
	{
		english: 'ocean',
		turkish: 'okyanus',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The ocean is vast and deep.', 'She loves swimming in the ocean.'],
		etymology: "The word 'ocean' has Latin origins.",
		additionalInformation: "Oceans cover about 70% of the Earth's surface."
	},
	{
		english: 'mountain',
		turkish: 'dağ',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The mountain peak is covered in snow.', 'She enjoys hiking in the mountains.'],
		etymology: "The word 'mountain' has Old French origins.",
		additionalInformation: 'Mountains are landforms that rise high above the surrounding terrain.'
	},
	{
		english: 'river',
		turkish: 'nehir',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The river flows through the valley.', 'She likes to sit by the river and watch the water flow.'],
		etymology: "The word 'river' has Old English origins.",
		additionalInformation: 'Rivers are natural watercourses that flow towards an ocean or sea.'
	},
	{
		english: 'lake',
		turkish: 'göl',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The lake is surrounded by mountains.', 'She went fishing at the lake.'],
		etymology: "The word 'lake' has Old English origins.",
		additionalInformation: 'Lakes are large bodies of water surrounded by land.'
	},
	{
		english: 'beach',
		turkish: 'plaj',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The beach is crowded with tourists.', 'She enjoys sunbathing on the beach.'],
		etymology: "The word 'beach' has Old English origins.",
		additionalInformation: 'Beaches are sandy or pebbly shorelines along a body of water.'
	},
	{
		english: 'guitar',
		turkish: 'gitar',
		category: 'Music',
		difficulty: 2,
		exampleSentences: ['He plays the guitar in a band.', 'She is learning to play the guitar.'],
		etymology: "The word 'guitar' has Spanish origins.",
		additionalInformation: 'Guitars are stringed musical instruments that produce sound by vibrating strings.'
	},
	{
		english: 'music',
		turkish: 'müzik',
		category: 'Arts',
		difficulty: 1,
		exampleSentences: ['I listen to music every day.', 'She enjoys playing music on her piano.'],
		etymology: "The word 'music' has Latin origins.",
		additionalInformation: 'Music is an art form that uses sound and silence to create harmony and expression.'
	},
	{
		english: 'coffee',
		turkish: 'kahve',
		category: 'Food and Drink',
		difficulty: 1,
		exampleSentences: ['I drink coffee in the morning.', 'She likes her coffee with milk and sugar.'],
		etymology: "The word 'coffee' has Arabic origins.",
		additionalInformation: 'Coffee is a popular beverage made from roasted coffee beans.'
	},
	{
		english: 'tea',
		turkish: 'çay',
		category: 'Food and Drink',
		difficulty: 1,
		exampleSentences: ['She enjoys drinking tea with lemon.', 'I prefer black tea over green tea.'],
		etymology: "The word 'tea' has Chinese origins.",
		additionalInformation: 'Tea is a beverage made from the leaves of the Camellia sinensis plant.'
	},
	{
		english: 'airplane',
		turkish: 'uçak',
		category: 'Transportation',
		difficulty: 2,
		exampleSentences: ['The airplane landed safely.', 'She travels by airplane often.'],
		etymology: "The word 'airplane' is derived from the combination of 'air' and 'plane'.",
		additionalInformation: 'Airplanes are a common mode of long-distance transportation.'
	},
	{
		english: 'bicycle',
		turkish: 'bisiklet',
		category: 'Transportation',
		difficulty: 1,
		exampleSentences: ['I ride my bicycle to school.', 'She enjoys cycling in the park.'],
		etymology: "The word 'bicycle' comes from the Greek words 'bi' meaning two, and 'kyklos' meaning wheel.",
		additionalInformation: 'Bicycles are a popular form of exercise and transport.'
	},
	{
		english: 'pencil',
		turkish: 'kalem',
		category: 'Stationery',
		difficulty: 1,
		exampleSentences: ['I write with a pencil.', 'She sharpened her pencil.'],
		etymology: "The word 'pencil' comes from the Latin word 'pencillus', meaning 'little tail'.",
		additionalInformation: 'Pencils are commonly used for writing and drawing.'
	},
	{
		english: 'giraffe',
		turkish: 'zürafa',
		category: 'Animals',
		difficulty: 3,
		exampleSentences: ['The giraffe has a long neck.', 'She saw a giraffe at the zoo.'],
		etymology: "The word 'giraffe' comes from the Arabic word 'zarāfa'.",
		additionalInformation: 'Giraffes are the tallest land animals.'
	},
	{
		english: 'restaurant',
		turkish: 'restoran',
		category: 'Places',
		difficulty: 2,
		exampleSentences: ['We ate dinner at a nice restaurant.', 'She owns a small restaurant.'],
		etymology: "The word 'restaurant' comes from the French word 'restaurer', meaning 'to restore'.",
		additionalInformation: 'Restaurants serve food and drinks to customers.'
	},
	{
		english: 'elephant',
		turkish: 'fil',
		category: 'Animals',
		difficulty: 2,
		exampleSentences: ['The elephant is a large animal.', 'She watched the elephant at the circus.'],
		etymology: "The word 'elephant' comes from the Latin word 'elephas'.",
		additionalInformation: 'Elephants are known for their large ears and trunks.'
	},
	{
		english: 'umbrella',
		turkish: 'şemsiye',
		category: 'Objects',
		difficulty: 1,
		exampleSentences: ['I carry an umbrella when it rains.', 'She bought a colorful umbrella.'],
		etymology: "The word 'umbrella' comes from the Latin word 'umbra', meaning 'shade'.",
		additionalInformation: 'Umbrellas are used to protect against rain and sunlight.'
	},
	{
		english: 'kangaroo',
		turkish: 'kanguru',
		category: 'Animals',
		difficulty: 3,
		exampleSentences: ['The kangaroo jumps high.', 'She saw a kangaroo in Australia.'],
		etymology: "The word 'kangaroo' comes from the Guugu Yimithirr word 'gangurru'.",
		additionalInformation: 'Kangaroos are marsupials native to Australia.'
	},
	{
		english: 'notebook',
		turkish: 'defter',
		category: 'Stationery',
		difficulty: 1,
		exampleSentences: ['I write my notes in a notebook.', 'She bought a new notebook for school.'],
		etymology: "The word 'notebook' comes from 'note' and 'book'.",
		additionalInformation: 'Notebooks are used for writing notes and information.'
	},
	{
		english: 'chocolate',
		turkish: 'çikolata',
		category: 'Food and Drink',
		difficulty: 1,
		exampleSentences: ['I love eating chocolate.', 'She gave me a box of chocolates.'],
		etymology: "The word 'chocolate' comes from the Nahuatl word 'chocolātl'.",
		additionalInformation: 'Chocolate is made from roasted and ground cacao seeds.'
	},
	{
		english: 'bridge',
		turkish: 'köprü',
		category: 'Structures',
		difficulty: 2,
		exampleSentences: ['The bridge crosses the river.', 'She walked across the bridge.'],
		etymology: "The word 'bridge' comes from Old English 'brycg'.",
		additionalInformation: 'Bridges are structures built to span physical obstacles.'
	},
	{
		english: 'island',
		turkish: 'ada',
		category: 'Geography',
		difficulty: 2,
		exampleSentences: ['The island is surrounded by water.', 'She visited a tropical island.'],
		etymology: "The word 'island' comes from Old English 'īegland'.",
		additionalInformation: 'Islands are landmasses surrounded by water.'
	},
	{
		english: 'garden',
		turkish: 'bahçe',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The garden is full of flowers.', 'She works in the garden every weekend.'],
		etymology: "The word 'garden' comes from Old French 'gardin'.",
		additionalInformation: 'Gardens are spaces for growing plants and flowers.'
	},
	{
		english: 'piano',
		turkish: 'piyano',
		category: 'Music',
		difficulty: 2,
		exampleSentences: ['He plays the piano beautifully.', 'She takes piano lessons every week.'],
		etymology: "The word 'piano' is short for 'pianoforte', which comes from Italian.",
		additionalInformation: 'The piano is a keyboard musical instrument.'
	},
	{
		english: 'library',
		turkish: 'kütüphane',
		category: 'Places',
		difficulty: 2,
		exampleSentences: ['I borrowed a book from the library.', 'She studies at the library.'],
		etymology: "The word 'library' comes from the Latin word 'librarium'.",
		additionalInformation: 'Libraries are places where books and other media are available for borrowing or reference.'
	},
	{
		english: 'banana',
		turkish: 'muz',
		category: 'Fruits',
		difficulty: 1,
		exampleSentences: ['I had a banana for lunch.', 'She likes banana smoothies.'],
		etymology: "The word 'banana' comes from the Wolof word 'banana'.",
		additionalInformation: 'Bananas are rich in potassium and vitamins.'
	},
	{
		english: 'mountain',
		turkish: 'dağ',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The mountain peak is covered in snow.', 'She enjoys hiking in the mountains.'],
		etymology: "The word 'mountain' has Old French origins.",
		additionalInformation: 'Mountains are landforms that rise high above the surrounding terrain.'
	},
	{
		english: 'pencil',
		turkish: 'kalem',
		category: 'Stationery',
		difficulty: 1,
		exampleSentences: ['I write with a pencil.', 'She sharpened her pencil.'],
		etymology: "The word 'pencil' comes from the Latin word 'pencillus', meaning 'little tail'.",
		additionalInformation: 'Pencils are commonly used for writing and drawing.'
	},
	{
		english: 'rainbow',
		turkish: 'gökkuşağı',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The rainbow appeared after the rain.', 'She loves the colors of the rainbow.'],
		etymology: "The word 'rainbow' comes from Old English 'regnboga'.",
		additionalInformation: 'Rainbows are caused by the refraction and dispersion of light in water droplets.'
	},
	{
		english: 'submarine',
		turkish: 'denizaltı',
		category: 'Transportation',
		difficulty: 3,
		exampleSentences: ['The submarine explored the ocean depths.', 'She watched a documentary about submarines.'],
		etymology: "The word 'submarine' comes from Latin 'submarinus', meaning 'under the sea'.",
		additionalInformation: 'Submarines are watercraft capable of underwater operation.'
	},
	{
		english: 'eagle',
		turkish: 'kartal',
		category: 'Animals',
		difficulty: 2,
		exampleSentences: ['The eagle soared high in the sky.', 'She saw an eagle during her hike.'],
		etymology: "The word 'eagle' comes from Old French 'aigle'.",
		additionalInformation: 'Eagles are large birds of prey known for their keen eyesight.'
	},
	{
		english: 'museum',
		turkish: 'müze',
		category: 'Places',
		difficulty: 2,
		exampleSentences: ['We visited the art museum.', 'She works at the history museum.'],
		etymology: "The word 'museum' comes from the Latin word 'museum', which means 'place of the Muses'.",
		additionalInformation: 'Museums are institutions that preserve and exhibit artifacts and artworks.'
	},
	{
		english: 'flower',
		turkish: 'çiçek',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The flower is blooming.', 'She picked a beautiful flower.'],
		etymology: "The word 'flower' comes from Old French 'flor'.",
		additionalInformation: 'Flowers are the reproductive structures of flowering plants.'
	},
	{
		english: 'mountain',
		turkish: 'dağ',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The mountain peak is covered in snow.', 'She enjoys hiking in the mountains.'],
		etymology: "The word 'mountain' has Old French origins.",
		additionalInformation: 'Mountains are landforms that rise high above the surrounding terrain.'
	},
	{
		english: 'ocean',
		turkish: 'okyanus',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The ocean is vast and deep.', 'She loves swimming in the ocean.'],
		etymology: "The word 'ocean' has Latin origins.",
		additionalInformation: "Oceans cover about 70% of the Earth's surface."
	},
	{
		english: 'music',
		turkish: 'müzik',
		category: 'Arts',
		difficulty: 1,
		exampleSentences: ['I listen to music every day.', 'She enjoys playing music on her piano.'],
		etymology: "The word 'music' has Latin origins.",
		additionalInformation: 'Music is an art form that uses sound and silence to create harmony and expression.'
	},
	{
		english: 'zebra',
		turkish: 'zebra',
		category: 'Animals',
		difficulty: 2,
		exampleSentences: ['The zebra has black and white stripes.', 'She saw a zebra at the safari park.'],
		etymology: "The word 'zebra' comes from the Portuguese word 'zebra'.",
		additionalInformation: 'Zebras are native to Africa and known for their distinct striped coats.'
	},
	{
		english: 'volcano',
		turkish: 'yanardağ',
		category: 'Nature',
		difficulty: 3,
		exampleSentences: ['The volcano erupted violently.', 'She learned about volcanoes in science class.'],
		etymology: "The word 'volcano' comes from the Latin word 'Vulcanus', the Roman god of fire.",
		additionalInformation: 'Volcanoes are geological formations that result from the eruption of molten rock.'
	},
	{
		english: 'castle',
		turkish: 'kale',
		category: 'Structures',
		difficulty: 2,
		exampleSentences: ['The castle is a historical monument.', 'She visited a medieval castle.'],
		etymology: "The word 'castle' comes from the Latin word 'castellum'.",
		additionalInformation: 'Castles are fortified structures built in the Middle Ages.'
	},
	{
		english: 'jungle',
		turkish: 'orman',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The jungle is dense and wild.', 'She explored the jungle during her trip.'],
		etymology: "The word 'jungle' comes from the Hindi word 'jangal'.",
		additionalInformation: 'Jungles are tropical forests with dense vegetation.'
	},
	{
		english: 'pyramid',
		turkish: 'piramit',
		category: 'Structures',
		difficulty: 3,
		exampleSentences: ['The pyramid is an ancient structure.', 'She visited the pyramids in Egypt.'],
		etymology: "The word 'pyramid' comes from the Greek word 'pyramis'.",
		additionalInformation: 'Pyramids are monumental structures with a square or triangular base and sloping sides.'
	},
	{
		english: 'robot',
		turkish: 'robot',
		category: 'Technology',
		difficulty: 2,
		exampleSentences: ['The robot can perform many tasks.', 'She built a robot for her science project.'],
		etymology: "The word 'robot' comes from the Czech word 'robota', meaning 'forced labor'.",
		additionalInformation: 'Robots are machines capable of carrying out complex tasks automatically.'
	},
	{
		english: 'desert',
		turkish: 'çöl',
		category: 'Geography',
		difficulty: 2,
		exampleSentences: ['The desert is hot and dry.', 'She crossed the desert on a camel.'],
		etymology: "The word 'desert' comes from the Latin word 'desertum', meaning 'abandoned place'.",
		additionalInformation: 'Deserts are arid regions with little precipitation.'
	},
	{
		english: 'comet',
		turkish: 'kuyruklu yıldız',
		category: 'Astronomy',
		difficulty: 3,
		exampleSentences: ['The comet was visible in the night sky.', 'She read about comets in her astronomy book.'],
		etymology: "The word 'comet' comes from the Greek word 'komētēs', meaning 'long-haired star'.",
		additionalInformation: 'Comets are icy bodies that release gas and dust, forming a glowing coma and tail.'
	},
	{
		english: 'laptop',
		turkish: 'dizüstü bilgisayar',
		category: 'Technology',
		difficulty: 1,
		exampleSentences: ['I use my laptop for work.', 'She bought a new laptop.'],
		etymology: "The word 'laptop' comes from 'lap' and 'top', indicating a computer small enough to be used on one's lap.",
		additionalInformation: 'Laptops are portable computers.'
	},
	{
		english: 'hospital',
		turkish: 'hastane',
		category: 'Places',
		difficulty: 2,
		exampleSentences: ['He was admitted to the hospital.', 'She works as a nurse at the hospital.'],
		etymology: "The word 'hospital' comes from the Latin word 'hospes', meaning 'guest'.",
		additionalInformation: 'Hospitals provide medical treatment and care for patients.'
	},
	{
		english: 'planet',
		turkish: 'gezegen',
		category: 'Astronomy',
		difficulty: 2,
		exampleSentences: ['Earth is a planet in the solar system.', 'She studied the planets in her science class.'],
		etymology: "The word 'planet' comes from the Greek word 'planētēs', meaning 'wanderer'.",
		additionalInformation: 'Planets are celestial bodies that orbit a star.'
	},
	{
		english: 'recipe',
		turkish: 'tarif',
		category: 'Food and Drink',
		difficulty: 2,
		exampleSentences: ['She followed a recipe to bake a cake.', "He shared his grandmother's recipe."],
		etymology: "The word 'recipe' comes from the Latin word 'recipere', meaning 'to receive'.",
		additionalInformation: 'Recipes provide instructions for preparing food and drinks.'
	},
	{
		english: 'cloud',
		turkish: 'bulut',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The sky is covered with clouds.', 'She loves watching the clouds.'],
		etymology: "The word 'cloud' comes from Old English 'clud', meaning 'rock, hill'.",
		additionalInformation: 'Clouds are visible masses of condensed water vapor in the atmosphere.'
	},
	{
		english: 'keyboard',
		turkish: 'klavye',
		category: 'Technology',
		difficulty: 1,
		exampleSentences: ['I type on my keyboard.', 'She spilled coffee on her keyboard.'],
		etymology: "The word 'keyboard' comes from 'key' and 'board'.",
		additionalInformation: 'Keyboards are input devices used to type text and commands into a computer.'
	},
	{
		english: 'radio',
		turkish: 'radyo',
		category: 'Technology',
		difficulty: 1,
		exampleSentences: ['She listens to the radio every morning.', 'The radio is playing my favorite song.'],
		etymology: "The word 'radio' comes from the Latin word 'radius', meaning 'ray'.",
		additionalInformation: 'Radios are devices that receive and transmit audio signals through electromagnetic waves.'
	},
	{
		english: 'train',
		turkish: 'tren',
		category: 'Transportation',
		difficulty: 1,
		exampleSentences: ['I take the train to work.', 'She enjoys traveling by train.'],
		etymology: "The word 'train' comes from Old French 'trahiner', meaning 'to pull, draw'.",
		additionalInformation: 'Trains are a mode of transportation that run on tracks.'
	},
	{
		english: 'engineer',
		turkish: 'mühendis',
		category: 'Professions',
		difficulty: 2,
		exampleSentences: ['He works as a mechanical engineer.', 'She studied engineering at university.'],
		etymology: "The word 'engineer' comes from the Latin word 'ingeniator', meaning 'one who devises'.",
		additionalInformation: 'Engineers design, build, and maintain structures, machines, and systems.'
	},
	{
		english: 'chef',
		turkish: 'şef',
		category: 'Professions',
		difficulty: 2,
		exampleSentences: ['The chef prepared a gourmet meal.', 'She is a chef at a famous restaurant.'],
		etymology: "The word 'chef' comes from the French word 'chef de cuisine', meaning 'head of the kitchen'.",
		additionalInformation: 'Chefs are professional cooks responsible for meal preparation and kitchen management.'
	},
	{
		english: 'garden',
		turkish: 'bahçe',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The garden is full of flowers.', 'She works in the garden every weekend.'],
		etymology: "The word 'garden' comes from Old French 'gardin'.",
		additionalInformation: 'Gardens are spaces for growing plants and flowers.'
	},
	{
		english: 'mountain',
		turkish: 'dağ',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The mountain peak is covered in snow.', 'She enjoys hiking in the mountains.'],
		etymology: "The word 'mountain' has Old French origins.",
		additionalInformation: 'Mountains are landforms that rise high above the surrounding terrain.'
	},
	{
		english: 'library',
		turkish: 'kütüphane',
		category: 'Places',
		difficulty: 2,
		exampleSentences: ['I borrowed a book from the library.', 'She studies at the library.'],
		etymology: "The word 'library' comes from the Latin word 'librarium'.",
		additionalInformation: 'Libraries are places where books and other media are available for borrowing or reference.'
	},
	{
		english: 'banana',
		turkish: 'muz',
		category: 'Fruits',
		difficulty: 1,
		exampleSentences: ['I had a banana for lunch.', 'She likes banana smoothies.'],
		etymology: "The word 'banana' comes from the Wolof word 'banana'.",
		additionalInformation: 'Bananas are rich in potassium and vitamins.'
	},
	{
		english: 'piano',
		turkish: 'piyano',
		category: 'Music',
		difficulty: 2,
		exampleSentences: ['He plays the piano beautifully.', 'She takes piano lessons every week.'],
		etymology: "The word 'piano' is short for 'pianoforte', which comes from Italian.",
		additionalInformation: 'The piano is a keyboard musical instrument.'
	},
	{
		english: 'guitar',
		turkish: 'gitar',
		category: 'Music',
		difficulty: 2,
		exampleSentences: ['He plays the guitar in a band.', 'She is learning to play the guitar.'],
		etymology: "The word 'guitar' has Spanish origins.",
		additionalInformation: 'Guitars are stringed musical instruments that produce sound by vibrating strings.'
	},
	{
		english: 'garden',
		turkish: 'bahçe',
		category: 'Nature',
		difficulty: 1,
		exampleSentences: ['The garden is full of flowers.', 'She works in the garden every weekend.'],
		etymology: "The word 'garden' comes from Old French 'gardin'.",
		additionalInformation: 'Gardens are spaces for growing plants and flowers.'
	},
	{
		english: 'mountain',
		turkish: 'dağ',
		category: 'Nature',
		difficulty: 2,
		exampleSentences: ['The mountain peak is covered in snow.', 'She enjoys hiking in the mountains.'],
		etymology: "The word 'mountain' has Old French origins.",
		additionalInformation: 'Mountains are landforms that rise high above the surrounding terrain.'
	},
	{
		english: 'library',
		turkish: 'kütüphane',
		category: 'Places',
		difficulty: 2,
		exampleSentences: ['I borrowed a book from the library.', 'She studies at the library.'],
		etymology: "The word 'library' comes from the Latin word 'librarium'.",
		additionalInformation: 'Libraries are places where books and other media are available for borrowing or reference.'
	},
	{
		english: 'banana',
		turkish: 'muz',
		category: 'Fruits',
		difficulty: 1,
		exampleSentences: ['I had a banana for lunch.', 'She likes banana smoothies.'],
		etymology: "The word 'banana' comes from the Wolof word 'banana'.",
		additionalInformation: 'Bananas are rich in potassium and vitamins.'
	}
];

export const quizData1 = {
	title: 'Basic English Vocabulary',
	quiz: [
		{
			question: "What is the English word for 'kitap'?",
			options: ['Book', 'Pen', 'Chair', 'Table'],
			correctAnswer: 'Book'
		},
		{
			question: "What is the English word for 'kalem'?",
			options: ['Eraser', 'Book', 'Pen', 'Notebook'],
			correctAnswer: 'Pen'
		},
		{
			question: "What is the English word for 'masa'?",
			options: ['Chair', 'Table', 'Sofa', 'Bed'],
			correctAnswer: 'Table'
		},
		{
			question: "What is the English word for 'defter'?",
			options: ['Notebook', 'Bag', 'Paper', 'Pencil'],
			correctAnswer: 'Notebook'
		},
		{
			question: "What is the English word for 'sandalye'?",
			options: ['Table', 'Chair', 'Window', 'Door'],
			correctAnswer: 'Chair'
		},
		{
			question: "What is the English word for 'çanta'?",
			options: ['Bag', 'Bottle', 'Box', 'Glass'],
			correctAnswer: 'Bag'
		},
		{
			question: "What is the English word for 'kapı'?",
			options: ['Window', 'Wall', 'Ceiling', 'Door'],
			correctAnswer: 'Door'
		},
		{
			question: "What is the English word for 'kalem kutusu'?",
			options: ['Pencil case', 'Pencil sharpener', 'Pencil', 'Case'],
			correctAnswer: 'Pencil case'
		}
	],
	published: true
};

export const quizData2 = {
	title: 'Common English Phrases',
	quiz: [
		{
			question: "What does 'How are you?' mean?",
			options: ['What is your name?', 'How old are you?', 'How are you?', 'Where do you live?'],
			correctAnswer: 'How are you?'
		},
		{
			question: "What is the response to 'Thank you'?",
			options: ['Please', "You're welcome", 'Excuse me', 'Sorry'],
			correctAnswer: "You're welcome"
		},
		{
			question: "What does 'Good morning' mean?",
			options: ['Good night', 'Good afternoon', 'Good morning', 'Goodbye'],
			correctAnswer: 'Good morning'
		},
		{
			question: "What is the English phrase for 'Hoşçakal'?",
			options: ['Hello', 'Goodbye', 'Please', 'Thank you'],
			correctAnswer: 'Goodbye'
		},
		{
			question: "What does 'Excuse me' mean?",
			options: ['Sorry', 'Thank you', 'Please', 'Excuse me'],
			correctAnswer: 'Excuse me'
		},
		{
			question: "What is the response to 'How are you?'",
			options: ['Fine, thank you', 'Yes, please', 'No, thank you', 'I am hungry'],
			correctAnswer: 'Fine, thank you'
		},
		{
			question: "What does 'Good night' mean?",
			options: ['Good morning', 'Good afternoon', 'Good night', 'Goodbye'],
			correctAnswer: 'Good night'
		},
		{
			question: "What is the English phrase for 'Teşekkür ederim'?",
			options: ['Sorry', 'Excuse me', 'Please', 'Thank you'],
			correctAnswer: 'Thank you'
		}
	],
	published: true
};
